# GitHub Actions workflow for testing Go applications with Ferrite
# Copy this file to .github/workflows/test.yml in your repository

name: Go CI with Ferrite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      ferrite:
        image: ghcr.io/josedab/ferrite:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "ferrite-cli PING"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Download dependencies
        run: go mod download

      - name: Wait for Ferrite
        run: |
          for i in {1..30}; do
            if nc -z localhost 6379; then
              echo "Ferrite is ready!"
              break
            fi
            echo "Waiting for Ferrite..."
            sleep 1
          done

      - name: Run tests
        run: go test -v -race ./...
        env:
          FERRITE_HOST: localhost
          FERRITE_PORT: "6379"
          REDIS_URL: redis://localhost:6379

      - name: Run tests with coverage
        run: go test -v -coverprofile=coverage.out ./...
        env:
          FERRITE_HOST: localhost
          FERRITE_PORT: "6379"

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.out

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
