# GitHub Actions workflow for testing Node.js applications with Ferrite
# Copy this file to .github/workflows/test.yml in your repository

name: Node.js CI with Ferrite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      ferrite:
        image: ghcr.io/josedab/ferrite:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "ferrite-cli PING"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for Ferrite
        run: |
          for i in {1..30}; do
            if nc -z localhost 6379; then
              echo "Ferrite is ready!"
              break
            fi
            echo "Waiting for Ferrite..."
            sleep 1
          done

      - name: Run tests
        run: npm test
        env:
          FERRITE_HOST: localhost
          FERRITE_PORT: 6379
          REDIS_URL: redis://localhost:6379

      - name: Run integration tests
        run: npm run test:integration
        env:
          FERRITE_HOST: localhost
          FERRITE_PORT: 6379
