# GitHub Actions workflow for testing Rust applications with Ferrite
# Copy this file to .github/workflows/test.yml in your repository

name: Rust CI with Ferrite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      ferrite:
        image: ghcr.io/josedab/ferrite:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "ferrite-cli PING"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2

      - name: Wait for Ferrite
        run: |
          for i in {1..30}; do
            if nc -z localhost 6379; then
              echo "Ferrite is ready!"
              break
            fi
            echo "Waiting for Ferrite..."
            sleep 1
          done

      - name: Run tests
        run: cargo test --verbose
        env:
          FERRITE_HOST: localhost
          FERRITE_PORT: "6379"
          REDIS_URL: redis://localhost:6379

      - name: Run tests with all features
        run: cargo test --verbose --all-features
        env:
          FERRITE_HOST: localhost
          FERRITE_PORT: "6379"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy -- -D warnings

  coverage:
    runs-on: ubuntu-latest

    services:
      ferrite:
        image: ghcr.io/josedab/ferrite:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "ferrite-cli PING"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate coverage
        run: cargo llvm-cov --lcov --output-path lcov.info
        env:
          FERRITE_HOST: localhost
          FERRITE_PORT: "6379"

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
