//! Protobuf-equivalent Rust types for the gRPC API.
//!
//! These types mirror what would be generated by `prost` from `.proto` files,
//! allowing the service layer to be defined without heavy compile-time dependencies.
//! When tonic/prost is connected, these types can be replaced by generated code.

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Shared types
// ---------------------------------------------------------------------------

/// A key-value pair used in batch and hash operations.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KeyValue {
    /// The key name.
    pub key: String,
    /// The raw value bytes.
    pub value: Vec<u8>,
}

// ---------------------------------------------------------------------------
// Request types
// ---------------------------------------------------------------------------

/// Request to retrieve a single key.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetRequest {
    /// The key to retrieve.
    pub key: String,
    /// Database index.
    pub database: u8,
}

/// Request to set a key to a value.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SetRequest {
    /// The key to set.
    pub key: String,
    /// The raw value bytes.
    pub value: Vec<u8>,
    /// Database index.
    pub database: u8,
    /// Optional TTL in milliseconds.
    pub ttl_ms: Option<u64>,
    /// Only set if key does **not** exist.
    pub nx: bool,
    /// Only set if key **already** exists.
    pub xx: bool,
}

/// Request to delete one or more keys.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeleteRequest {
    /// Keys to delete.
    pub keys: Vec<String>,
    /// Database index.
    pub database: u8,
}

/// Request to check existence of one or more keys.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExistsRequest {
    /// Keys to check.
    pub keys: Vec<String>,
    /// Database index.
    pub database: u8,
}

/// Request to retrieve multiple keys at once.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MGetRequest {
    /// Keys to retrieve.
    pub keys: Vec<String>,
    /// Database index.
    pub database: u8,
}

/// Request to set multiple key-value pairs at once.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MSetRequest {
    /// Key-value pairs to set.
    pub entries: Vec<KeyValue>,
    /// Database index.
    pub database: u8,
}

/// Request to incrementally iterate over keys.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScanRequest {
    /// Current cursor position (0 to start).
    pub cursor: u64,
    /// Optional glob-style pattern filter.
    pub pattern: Option<String>,
    /// Hint for how many keys to return per call.
    pub count: Option<u64>,
    /// Database index.
    pub database: u8,
}

/// Request to increment a key by an integer amount.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IncrRequest {
    /// The key to increment.
    pub key: String,
    /// Amount to add (may be negative).
    pub increment: i64,
    /// Database index.
    pub database: u8,
}

/// Request to push values onto a list.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListPushRequest {
    /// List key.
    pub key: String,
    /// Values to push.
    pub values: Vec<Vec<u8>>,
    /// Push to the left (head) when `true`, right (tail) when `false`.
    pub left: bool,
    /// Database index.
    pub database: u8,
}

/// Request to pop values from a list.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListPopRequest {
    /// List key.
    pub key: String,
    /// Number of elements to pop.
    pub count: u32,
    /// Pop from the left (head) when `true`, right (tail) when `false`.
    pub left: bool,
    /// Database index.
    pub database: u8,
}

/// Request to set fields on a hash.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HashSetRequest {
    /// Hash key.
    pub key: String,
    /// Fields to set.
    pub fields: Vec<KeyValue>,
    /// Database index.
    pub database: u8,
}

/// Request to get fields from a hash.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HashGetRequest {
    /// Hash key.
    pub key: String,
    /// Field names to retrieve.
    pub fields: Vec<String>,
    /// Database index.
    pub database: u8,
}

/// Request to subscribe to channels / patterns.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscribeRequest {
    /// Channel names to subscribe to.
    pub channels: Vec<String>,
    /// Glob patterns to subscribe to.
    pub patterns: Vec<String>,
}

/// Request to publish a message to a channel.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PublishRequest {
    /// Target channel name.
    pub channel: String,
    /// Message payload.
    pub message: Vec<u8>,
}

/// Ping health-check request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PingRequest {
    /// Optional message to echo back.
    pub message: Option<String>,
}

/// Request for server information.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InfoRequest {
    /// Info sections to return (empty = all).
    pub sections: Vec<String>,
}

/// A batch of operations to execute atomically.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchRequest {
    /// Ordered list of operations to execute.
    pub operations: Vec<Operation>,
}

/// A single operation inside a [`BatchRequest`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Operation {
    /// Get a key.
    Get(GetRequest),
    /// Set a key-value pair.
    Set(SetRequest),
    /// Delete one or more keys.
    Delete(DeleteRequest),
    /// Check existence of keys.
    Exists(ExistsRequest),
    /// Increment a key by an integer amount.
    Incr(IncrRequest),
}

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/// Response for a single-key get.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GetResponse {
    /// The value bytes, if found.
    pub value: Option<Vec<u8>>,
    /// Whether the key exists.
    pub found: bool,
}

/// Response for a set operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SetResponse {
    /// Whether the set was performed.
    pub success: bool,
    /// Previous value, if any.
    pub old_value: Option<Vec<u8>>,
}

/// Response for a delete operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeleteResponse {
    /// Number of keys actually deleted.
    pub deleted_count: u64,
}

/// Response for an exists check.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExistsResponse {
    /// Number of keys that exist.
    pub exist_count: u64,
}

/// Response for a multi-get.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MGetResponse {
    /// Values in the same order as the requested keys; `None` for missing keys.
    pub values: Vec<Option<Vec<u8>>>,
}

/// Response for a multi-set.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MSetResponse {
    /// Whether the operation succeeded.
    pub success: bool,
}

/// Response for a scan iteration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScanResponse {
    /// Next cursor position (0 when iteration is complete).
    pub cursor: u64,
    /// Keys returned in this batch.
    pub keys: Vec<String>,
}

/// Response for an increment operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IncrResponse {
    /// New value after the increment.
    pub value: i64,
}

/// Response for a list push.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListPushResponse {
    /// New length of the list.
    pub length: u64,
}

/// Response for a list pop.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ListPopResponse {
    /// Popped values.
    pub values: Vec<Vec<u8>>,
}

/// Response for a hash set.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HashSetResponse {
    /// Number of fields that were newly created (not updated).
    pub new_fields: u64,
}

/// Response for a hash get.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HashGetResponse {
    /// Field values in request order; `None` for missing fields.
    pub values: Vec<Option<Vec<u8>>>,
}

/// Response for a ping.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PingResponse {
    /// Echoed message (defaults to "PONG").
    pub message: String,
}

/// Response for an info request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InfoResponse {
    /// Server information string.
    pub info: String,
}

/// Response for a batch operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BatchResponse {
    /// Results in the same order as the submitted operations.
    pub results: Vec<OperationResult>,
}

/// Result of a single operation within a batch.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OperationResult {
    /// Whether the operation succeeded.
    pub success: bool,
    /// Error message on failure.
    pub error: Option<String>,
    /// Optional result data.
    pub data: Option<Vec<u8>>,
}
