// Generated by `ferrite-fn new --lang go`
// Build:  tinygo build -o function.wasm -target=wasip2 main.go
// Deploy: ferrite-cli fn load <name> function.wasm
package main

// WASI P2 component model bindings will be generated from the Forge WIT files.
// Until official Go bindings are published, use wit-bindgen-go or manual FFI.
//
// See: https://github.com/AkihiroSuda/wasi-go

// process is the main entry point invoked by the Ferrite Forge runtime.
// It receives arbitrary bytes and returns processed bytes (or an error string).
//
//export process
func process(input []byte) ([]byte, error) {
	// Your function logic here.
	// Host imports (kv_get, kv_set, time_now_ms, log_info) are available
	// once WIT bindings are generated.
	return input, nil // Echo by default
}

func main() {}
