// Generated by `ferrite-fn new --lang ts`
// Build:  npx jco componentize index.js -w ../../../crates/ferrite-forge/wit -o function.wasm
// Deploy: ferrite-cli fn load <name> function.wasm

/**
 * Host imports provided by the Ferrite Forge runtime.
 * These are injected at instantiation time via the WIT contract.
 */
declare const kv: {
  get(key: string): Uint8Array | null;
  set(key: string, value: Uint8Array): void;
};
declare const time: { nowMs(): bigint };
declare const log: { info(msg: string): void };

/**
 * Main entry point — invoked by the Ferrite Forge runtime.
 *
 * @param input - Raw bytes passed to the function
 * @returns Processed bytes (or throws a string error)
 */
export function process(input: Uint8Array): Uint8Array {
  // Your function logic here.
  // Use `kv.get`, `kv.set`, `time.nowMs`, `log.info` host imports.
  return input; // Echo by default
}
