// Generated by `cargo ferrite-fn new`
// Build: cargo component build --release
// Deploy: ferrite-cli fn load <name> target/wasm32-wasip2/release/<name>.wasm

wit_bindgen::generate!({
    world: "function",
    path: "../../../crates/ferrite-forge/wit",
});

struct Component;

impl Guest for Component {
    fn process(input: Vec<u8>) -> Result<Vec<u8>, String> {
        // Your function logic here.
        // Use `kv::get`, `kv::set`, `time::now_ms`, `log::info` imports.
        Ok(input) // Echo by default
    }
}

export!(Component);
